apiVersion: v1
kind: PersistentVolumeClaim #requested for storage 
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-roboshop"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    purpose: efs-dynamic-demo 
    project: roboshop
spec:
  containers:
  - name: nginx  
    image: nginx   
    volumeMounts: # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html #It will be mounted inside the container at the folder&Path inside the container where the volume is attached
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
  labels: 
     purpose: efs-dynamic-demo 
     project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
