apiVersion: v1
kind: Pod
metadata:
  name: env-secret
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: pod-secret #pod refering secrete from envFrom 

